=== khoitran591-ktpm2211045/M-h-nh-ERD-nh-m-KKD/TruongHoc.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE TruongHoc [
    <!-- Định nghĩa các thực thể -->
    
    <!-- NIÊN KHÓA -->
    <!ELEMENT NienKhoa (MaNienKhoa, TenNienKhoa, NamBatDau, NamKetThuc, NgayBatDau, NgayKetThuc, MoTa)>
    <!ELEMENT MaNienKhoa (#PCDATA)>
    <!ELEMENT TenNienKhoa (#PCDATA)>
    <!ELEMENT NamBatDau (#PCDATA)>
    <!ELEMENT NamKetThuc (#PCDATA)>
    <!ELEMENT NgayBatDau (#PCDATA)>
    <!ELEMENT NgayKetThuc (#PCDATA)>
    <!ELEMENT MoTa (#PCDATA)>
    
    <!-- KHỐI LỚP -->
    <!ELEMENT KhoiLop (MaKhoi, TenKhoi, DoTuoi, MoTa)>
    <!ELEMENT MaKhoi (#PCDATA)>
    <!ELEMENT TenKhoi (#PCDATA)>
    <!ELEMENT DoTuoi (#PCDATA)>
    
    <!-- LỚP HỌC -->
    <!ELEMENT LopHoc (MaLop, MaKhoi, TenLop, SiSo, DanhSachHS, PhongHoc)>
    <!ELEMENT MaLop (#PCDATA)>
    <!ELEMENT TenLop (#PCDATA)>
    <!ELEMENT SiSo (#PCDATA)>
    <!ELEMENT DanhSachHS (#PCDATA)>
    <!ELEMENT PhongHoc (#PCDATA)>
    
    <!-- PHỤ HUYNH -->
    <!ELEMENT PhuHuynh (MaPH, HoTen, GioiTinh, DiaChi, SoDienThoai)>
    <!ELEMENT MaPH (#PCDATA)>
    <!ELEMENT HoTen (#PCDATA)>
    <!ELEMENT GioiTinh (#PCDATA)>
    <!ELEMENT DiaChi (#PCDATA)>
    <!ELEMENT SoDienThoai (#PCDATA)>
    
    <!-- HỌC SINH -->
    <!ELEMENT HocSinh (MaHS, MaPH, MaLop, HoTen, GioiTinh, Lop, SoDienThoai, NgaySinh)>
    <!ELEMENT MaHS (#PCDATA)>
    <!ELEMENT Lop (#PCDATA)>
    <!ELEMENT NgaySinh (#PCDATA)>
    
    <!-- ĐĂNG KÍ LỚP -->
    <!ELEMENT DangKiLop (MaDangKi, MaHocSinh, MaLop, MaNienKhoa, HocKi, NgayChuyenLop)>
    <!ELEMENT MaDangKi (#PCDATA)>
    <!ELEMENT MaHocSinh (#PCDATA)>
    <!ELEMENT HocKi (#PCDATA)>
    <!ELEMENT NgayChuyenLop (#PCDATA)>
    
    <!-- GIÁO VIÊN -->
    <!ELEMENT GiaoVien (MaGV, MaNhanVien, HoTen, GioiTinh, DiaChi, SoDienThoai, TrinhDo)>
    <!ELEMENT MaGV (#PCDATA)>
    <!ELEMENT MaNhanVien (#PCDATA)>
    <!ELEMENT TrinhDo (#PCDATA)>
    
    <!-- PHÂN CÔNG GIÁO VIÊN -->
    <!ELEMENT PhanCongGV (MaPhanCong, MaLop, MaGV)>
    <!ELEMENT MaPhanCong (#PCDATA)>
    
    <!-- ROOT ELEMENT -->
    <!ELEMENT TruongHoc (NienKhoa+, KhoiLop+, LopHoc+, PhuHuynh+, HocSinh+, DangKiLop+, GiaoVien+, PhanCongGV+)>
    
    <!-- ATTLIST cho các thuộc tính -->
    <!ATTLIST NienKhoa id ID #IMPLIED>
    <!ATTLIST KhoiLop id ID #IMPLIED>
    <!ATTLIST LopHoc id ID #IMPLIED>
    <!ATTLIST PhuHuynh id ID #IMPLIED>
    <!ATTLIST HocSinh id ID #IMPLIED>
    <!ATTLIST DangKiLop id ID #IMPLIED>
    <!ATTLIST GiaoVien id ID #IMPLIED>
    <!ATTLIST PhanCongGV id ID #IMPLIED>
]>

=== khoitran591-ktpm2211045/M-h-nh-ERD-nh-m-KKD/Bai_Nhom.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- 
    File XML thống nhất có thể sử dụng với cả DTD và XSD
    Để sử dụng với DTD: Uncomment dòng DOCTYPE và comment namespace
    Để sử dụng với XSD: Uncomment namespace và comment DOCTYPE
-->

<!-- CHO DTD: Uncomment dòng này -->
<!-- <!DOCTYPE TruongHoc SYSTEM "TruongHoc.dtd"> -->

<!-- CHO XSD: Uncomment các dòng này -->
<!-- <TruongHoc xmlns="http://www.truonghoc.edu.vn" 
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
           xsi:schemaLocation="http://www.truonghoc.edu.vn TruongHoc.xsd"> -->

<!-- CHO XML THUẦN: Sử dụng dòng này -->
<TruongHoc>
    <!-- NIÊN KHÓA -->
    <NienKhoa>
        <MaNienKhoa>1</MaNienKhoa>
        <TenNienKhoa>2023-2024</TenNienKhoa>
        <NamBatDau>2023</NamBatDau>
        <NamKetThuc>2024</NamKetThuc>
        <NgayBatDau>2023-09-05</NgayBatDau>
        <NgayKetThuc>2024-05-31</NgayKetThuc>
        <MoTa>Niên khóa học chính quy</MoTa>
    </NienKhoa>
    
    <NienKhoa>
        <MaNienKhoa>2</MaNienKhoa>
        <TenNienKhoa>2024-2025</TenNienKhoa>
        <NamBatDau>2024</NamBatDau>
        <NamKetThuc>2025</NamKetThuc>
        <NgayBatDau>2024-09-02</NgayBatDau>
        <NgayKetThuc>2025-05-30</NgayKetThuc>
        <MoTa>Niên khóa học chính quy</MoTa>
    </NienKhoa>
    
    <NienKhoa>
        <MaNienKhoa>3</MaNienKhoa>
        <TenNienKhoa>2022-2023</TenNienKhoa>
        <NamBatDau>2022</NamBatDau>
        <NamKetThuc>2023</NamKetThuc>
        <NgayBatDau>2022-09-05</NgayBatDau>
        <NgayKetThuc>2023-05-31</NgayKetThuc>
        <MoTa>Niên khóa học chính quy</MoTa>
    </NienKhoa>
    
    <NienKhoa>
        <MaNienKhoa>4</MaNienKhoa>
        <TenNienKhoa>2021-2022</TenNienKhoa>
        <NamBatDau>2021</NamBatDau>
        <NamKetThuc>2022</NamKetThuc>
        <NgayBatDau>2021-09-06</NgayBatDau>
        <NgayKetThuc>2022-05-30</NgayKetThuc>
        <MoTa>Niên khóa học chính quy</MoTa>
    </NienKhoa>
    
    <NienKhoa>
        <MaNienKhoa>5</MaNienKhoa>
        <TenNienKhoa>2020-2021</TenNienKhoa>
        <NamBatDau>2020</NamBatDau>
        <NamKetThuc>2021</NamKetThuc>
        <NgayBatDau>2020-09-07</NgayBatDau>
        <NgayKetThuc>2021-05-31</NgayKetThuc>
        <MoTa>Niên khóa học chính quy</MoTa>
    </NienKhoa>
    
    <NienKhoa>
        <MaNienKhoa>6</MaNienKhoa>
        <TenNienKhoa>2019-2020</TenNienKhoa>
        <NamBatDau>2019</NamBatDau>
        <NamKetThuc>2020</NamKetThuc>
        <NgayBatDau>2019-09-02</NgayBatDau>
        <NgayKetThuc>2020-05-29</NgayKetThuc>
        <MoTa>Niên khóa học chính quy</MoTa>
    </NienKhoa>
    
    <NienKhoa>
        <MaNienKhoa>7</MaNienKhoa>
        <TenNienKhoa>2018-2019</TenNienKhoa>
        <NamBatDau>2018</NamBatDau>
        <NamKetThuc>2019</NamKetThuc>
        <NgayBatDau>2018-09-03</NgayBatDau>
        <NgayKetThuc>2019-05-30</NgayKetThuc>
        <MoTa>Niên khóa học chính quy</MoTa>
    </NienKhoa>
    
    <NienKhoa>
        <MaNienKhoa>8</MaNienKhoa>
        <TenNienKhoa>2017-2018</TenNienKhoa>
        <NamBatDau>2017</NamBatDau>
        <NamKetThuc>2018</NamKetThuc>
        <NgayBatDau>2017-09-04</NgayBatDau>
        <NgayKetThuc>2018-05-31</NgayKetThuc>
        <MoTa>Niên khóa học chính quy</MoTa>
    </NienKhoa>

    <!-- KHỐI LỚP -->
    <KhoiLop>
        <MaKhoi>1</MaKhoi>
        <TenKhoi>Khối 1</TenKhoi>
        <DoTuoi>6</DoTuoi>
        <MoTa>Khối lớp 1 - Tiểu học</MoTa>
    </KhoiLop>
    
    <KhoiLop>
        <MaKhoi>2</MaKhoi>
        <TenKhoi>Khối 2</TenKhoi>
        <DoTuoi>7</DoTuoi>
        <MoTa>Khối lớp 2 - Tiểu học</MoTa>
    </KhoiLop>
    
    <KhoiLop>
        <MaKhoi>3</MaKhoi>
        <TenKhoi>Khối 3</TenKhoi>
        <DoTuoi>8</DoTuoi>
        <MoTa>Khối lớp 3 - Tiểu học</MoTa>
    </KhoiLop>
    
    <KhoiLop>
        <MaKhoi>4</MaKhoi>
        <TenKhoi>Khối 4</TenKhoi>
        <DoTuoi>9</DoTuoi>
        <MoTa>Khối lớp 4 - Tiểu học</MoTa>
    </KhoiLop>
    
    <KhoiLop>
        <MaKhoi>5</MaKhoi>
        <TenKhoi>Khối 5</TenKhoi>
        <DoTuoi>10</DoTuoi>
        <MoTa>Khối lớp 5 - Tiểu học</MoTa>
    </KhoiLop>
    
    <KhoiLop>
        <MaKhoi>6</MaKhoi>
        <TenKhoi>Khối 6</TenKhoi>
        <DoTuoi>11</DoTuoi>
        <MoTa>Khối lớp 6 - Trung học cơ sở</MoTa>
    </KhoiLop>
    
    <KhoiLop>
        <MaKhoi>7</MaKhoi>
        <TenKhoi>Khối 7</TenKhoi>
        <DoTuoi>12</DoTuoi>
        <MoTa>Khối lớp 7 - Trung học cơ sở</MoTa>
    </KhoiLop>
    
    <KhoiLop>
        <MaKhoi>8</MaKhoi>
        <TenKhoi>Khối 8</TenKhoi>
        <DoTuoi>13</DoTuoi>
        <MoTa>Khối lớp 8 - Trung học cơ sở</MoTa>
    </KhoiLop>
    
    <KhoiLop>
        <MaKhoi>9</MaKhoi>
        <TenKhoi>Khối 9</TenKhoi>
        <DoTuoi>14</DoTuoi>
        <MoTa>Khối lớp 9 - Trung học cơ sở</MoTa>
    </KhoiLop>

    <!-- LỚP HỌC -->
    <LopHoc>
        <MaLop>101</MaLop>
        <MaKhoi>1</MaKhoi>
        <TenLop>1A</TenLop>
        <SiSo>35</SiSo>
        <DanhSachHS />
        <PhongHoc>P101</PhongHoc>
    </LopHoc>
    
    <LopHoc>
        <MaLop>102</MaLop>
        <MaKhoi>1</MaKhoi>
        <TenLop>1B</TenLop>
        <SiSo>32</SiSo>
        <DanhSachHS />
        <PhongHoc>P102</PhongHoc>
    </LopHoc>
    
    <LopHoc>
        <MaLop>201</MaLop>
        <MaKhoi>2</MaKhoi>
        <TenLop>2A</TenLop>
        <SiSo>38</SiSo>
        <DanhSachHS />
        <PhongHoc>P201</PhongHoc>
    </LopHoc>
    
    <LopHoc>
        <MaLop>202</MaLop>
        <MaKhoi>2</MaKhoi>
        <TenLop>2B</TenLop>
        <SiSo>36</SiSo>
        <DanhSachHS />
        <PhongHoc>P202</PhongHoc>
    </LopHoc>
    
    <LopHoc>
        <MaLop>301</MaLop>
        <MaKhoi>3</MaKhoi>
        <TenLop>3A</TenLop>
        <SiSo>34</SiSo>
        <DanhSachHS />
        <PhongHoc>P301</PhongHoc>
    </LopHoc>
    
    <LopHoc>
        <MaLop>302</MaLop>
        <MaKhoi>3</MaKhoi>
        <TenLop>3B</TenLop>
        <SiSo>33</SiSo>
        <DanhSachHS />
        <PhongHoc>P302</PhongHoc>
    </LopHoc>
    
    <LopHoc>
        <MaLop>401</MaLop>
        <MaKhoi>4</MaKhoi>
        <TenLop>4A</TenLop>
        <SiSo>35</SiSo>
        <DanhSachHS />
        <PhongHoc>P401</PhongHoc>
    </LopHoc>
    
    <LopHoc>
        <MaLop>402</MaLop>
        <MaKhoi>4</MaKhoi>
        <TenLop>4B</TenLop>
        <SiSo>37</SiSo>
        <DanhSachHS />
        <PhongHoc>P402</PhongHoc>
    </LopHoc>
    
    <LopHoc>
        <MaLop>501</MaLop>
        <MaKhoi>5</MaKhoi>
        <TenLop>5A</TenLop>
        <SiSo>36</SiSo>
        <DanhSachHS />
        <PhongHoc>P501</PhongHoc>
    </LopHoc>
    
    <LopHoc>
        <MaLop>502</MaLop>
        <MaKhoi>5</MaKhoi>
        <TenLop>5B</TenLop>
        <SiSo>34</SiSo>
        <DanhSachHS />
        <PhongHoc>P502</PhongHoc>
    </LopHoc>

    <!-- PHỤ HUYNH -->
    <PhuHuynh>
        <MaPH>501</MaPH>
        <HoTen>Nguyễn Văn Minh</HoTen>
        <GioiTinh>Nam</GioiTinh>
        <DiaChi>123 Đường Lê Lợi, Quận Ninh Kiều, Cần Thơ</DiaChi>
        <SoDienThoai>0901234567</SoDienThoai>
    </PhuHuynh>
    
    <PhuHuynh>
        <MaPH>502</MaPH>
        <HoTen>Trần Thị Hoa</HoTen>
        <GioiTinh>Nữ</GioiTinh>
        <DiaChi>456 Đường Nguyễn Huệ, Quận Ninh Kiều, Cần Thơ</DiaChi>
        <SoDienThoai>0912345678</SoDienThoai>
    </PhuHuynh>
    
    <PhuHuynh>
        <MaPH>503</MaPH>
        <HoTen>Lê Văn Đức</HoTen>
        <GioiTinh>Nam</GioiTinh>
        <DiaChi>789 Đường Điện Biên Phủ, Quận Ninh Kiều, Cần Thơ</DiaChi>
        <SoDienThoai>0923456789</SoDienThoai>
    </PhuHuynh>
    
    <PhuHuynh>
        <MaPH>504</MaPH>
        <HoTen>Phạm Thị Lan</HoTen>
        <GioiTinh>Nữ</GioiTinh>
        <DiaChi>321 Đường Cách Mạng Tháng 8, Quận Ninh Kiều, Cần Thơ</DiaChi>
        <SoDienThoai>0934567890</SoDienThoai>
    </PhuHuynh>
    
    <PhuHuynh>
        <MaPH>505</MaPH>
        <HoTen>Hoàng Văn Thành</HoTen>
        <GioiTinh>Nam</GioiTinh>
        <DiaChi>654 Đường Lê Văn Việt, Quận Ninh Kiều, Cần Thơ</DiaChi>
        <SoDienThoai>0945678901</SoDienThoai>
    </PhuHuynh>
    
    <PhuHuynh>
        <MaPH>506</MaPH>
        <HoTen>Võ Thị Hồng</HoTen>
        <GioiTinh>Nữ</GioiTinh>
        <DiaChi>987 Đường Nguyễn Văn Linh, Quận Ninh Kiều, Cần Thơ</DiaChi>
        <SoDienThoai>0956789012</SoDienThoai>
    </PhuHuynh>
    
    <PhuHuynh>
        <MaPH>507</MaPH>
        <HoTen>Đặng Văn Sơn</HoTen>
        <GioiTinh>Nam</GioiTinh>
        <DiaChi>147 Đường Tân Sơn Nhì, Quận Ninh Kiều, Cần Thơ</DiaChi>
        <SoDienThoai>0967890123</SoDienThoai>
    </PhuHuynh>
    
    <PhuHuynh>
        <MaPH>508</MaPH>
        <HoTen>Bùi Thị Nga</HoTen>
        <GioiTinh>Nữ</GioiTinh>
        <DiaChi>258 Đường Lạc Long Quân, Quận Ninh Kiều, Cần Thơ</DiaChi>
        <SoDienThoai>0978901234</SoDienThoai>
    </PhuHuynh>
    
    <PhuHuynh>
        <MaPH>509</MaPH>
        <HoTen>Ngô Văn Đức</HoTen>
        <GioiTinh>Nam</GioiTinh>
        <DiaChi>369 Đường Phạm Văn Đồng, Quận Ninh Kiều, Cần Thơ</DiaChi>
        <SoDienThoai>0989012345</SoDienThoai>
    </PhuHuynh>
    
    <PhuHuynh>
        <MaPH>510</MaPH>
        <HoTen>Đỗ Thị Mai</HoTen>
        <GioiTinh>Nữ</GioiTinh>
        <DiaChi>741 Đường Nguyễn Thị Thập, Quận Ninh Kiều, Cần Thơ</DiaChi>
        <SoDienThoai>0990123456</SoDienThoai>
    </PhuHuynh>

    <!-- HỌC SINH -->
    <HocSinh>
        <MaHS>1001</MaHS>
        <MaPH>501</MaPH>
        <MaLop>101</MaLop>
        <HoTen>Nguyễn Minh An</HoTen>
        <GioiTinh>Nam</GioiTinh>
        <Lop>1A</Lop>
        <SoDienThoai>0901234567</SoDienThoai>
        <NgaySinh>2018-03-15</NgaySinh>
    </HocSinh>
    
    <HocSinh>
        <MaHS>1002</MaHS>
        <MaPH>502</MaPH>
